services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notesdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password123@db:5432/notesdb
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDER: ${SENDER}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: 5000
      NODE_ENV: production
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network
    command: >
      sh -c "npx prisma migrate deploy &&
             node dist/server.js"

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
